import React, { useContext } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { SectionTitle } from './../components/Global/SectionTitle';
import { PrimaryButton } from './../components/Global/PrimaryButton/PrimaryButton';
import { fetchWord } from '@/lang/fetchWord';
import { LanguageContext } from './../context/LangContext';
const Activation = () => {
  const { lang } = useContext(LanguageContext);
  return (
    <>
      <Head>
        <title>Verification</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mobile-container">
        <div className="flex gap-4 flex-col">
          <div className="">
            <h1 className="text-2xl mb-4 font-semibold">Verify Your Mail</h1>
            <p className="text-sm mb-4 text-[#00000099]">
              Please Enter 4-Digit Sent to your Mail
            </p>
          </div>
          <div className="flex gap-4 justify-between items-center mt-6">
            <input
              className="w-16 h-14 rounded-md border-2 bg-[#D9D9D980] text-center text-2xl focus:border-primary text-primary border-[#E5E5E5]"
              type="tel"
            />
            <input
              className="w-16 h-14 rounded-md border-2 bg-[#D9D9D980] text-center text-2xl focus:border-primary text-primary border-[#E5E5E5]"
              type="tel"
            />
            <input
              className="w-16 h-14 rounded-md border-2 bg-[#D9D9D980] text-center text-2xl focus:border-primary text-primary border-[#E5E5E5]"
              type="tel"
            />
            <input
              className="w-16 h-14 rounded-md border-2 bg-[#D9D9D980] text-center text-2xl focus:border-primary text-primary border-[#E5E5E5]"
              type="tel"
            />
          </div>
          <button className="text-primary underline block text-center mb-8 mt-4">
            Resend Code
          </button>
          <PrimaryButton
            text={fetchWord('verify', lang)}
            classes="max-w-[300px] w-full rounded-lg !py-3 mx-auto "
          />
        </div>
      </div>
    </>
  );
};
export default Activation;
