import { cart as carts } from '@/data/cardData';
import Head from 'next/head';
import { useEffect, useState, useContext } from 'react';

import { CartTotal } from './../components/CartComponents/CartTotal';
import { TableCart } from './../components/CartComponents/TableCart';
import { Layout } from './../components/Layout/Layout';
import { FormPromoCode } from './../components/CartComponents/FormPromoCode';
import { fetchWord } from './../lang/fetchWord';
import { LanguageContext } from './../context/LangContext';

export default function Cart() {
  const { lang } = useContext(LanguageContext);
  const [cart, setCart] = useState([]);
  useEffect(() => {
    setCart(carts);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title={fetchWord('cart', lang)}>
        <div className="mb-32">
          <TableCart cart={cart} />
          <FormPromoCode />
          <CartTotal cart={cart} />
        </div>
      </Layout>
    </>
  );
}
