import { fetchWord } from '@/lang/fetchWord';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext } from 'react';

import { Banner } from './../components/Banner/Banner';
import { BrowseOurCategories } from './../components/BrowseOurCategories/BrowseOurCategories';
import { Layout } from './../components/Layout/Layout';
import { WinterCollectionBanner } from './../components/WinterCollectionBanner/WinterCollectionBanner';
import { LanguageContext } from './../context/LangContext';
import { FeaturedProductGrid } from './../components/BrowseOurCategories/FeaturedProductGrid';
import { products } from '@/data/cardData';

export default function Home() {
  const { lang } = useContext(LanguageContext);

  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="mb-24">
          <Banner />
          <BrowseOurCategories title={fetchWord('FEATURED_PRODUCTS', lang)} />
          <WinterCollectionBanner />
          <div className="my-4" />
          <FeaturedProductGrid products={products} />
        </div>
      </Layout>
    </>
  );
}
